language: python
python:
    - "3.9"

env:
  TEST=True

install:
  - pip install -r requirements.txt
  - pip install coveralls
script:
  - coverage run --source=. -m unittest discover -s tests/f

after_success:
  - coveralls