services:
  db:
    image: mysql
    volumes:
      - ./data/db:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=mysql
      - MYSQL_PASSWORD=mysql
      - MYSQL_ROOT_PASSWORD=rootpassword
    ports:
      - "3306:3306"


  web:
    build: .
    environment:
      PYTHONPATH: /backend
    entrypoint: /backend/entrypoint.sh
    volumes:
      - .:/backend
    ports:
      - "5000:5000"
    env_file:
      - .env
    depends_on:
      - db